document.documentElement.setAttribute('translate','no');document.documentElement.classList.add('notranslate');document.body&&document.body.setAttribute('translate','no');if(!document.querySelector('meta[name="google"]')){const noTranslate=document.createElement('meta');noTranslate.name='google';noTranslate.content='notranslate';document.head.appendChild(noTranslate)}

const mobileFix=document.createElement('style');mobileFix.textContent=`html,body{max-width:100%;overflow-x:hidden}.hero-grid,.hero-copy,.hero-copy h1,.lead{min-width:0;max-width:100%}.hero-media{background-image:url('assets/images/living-room-v2.jpg')!important;background-position:center 45%!important}@media(max-width:640px){.hero{min-height:720px}.hero-grid{padding:130px 0 105px!important}.hero-copy{width:100%;overflow:hidden}.hero-copy h1{width:100%;max-width:100%;font-size:clamp(34px,9.4vw,40px)!important;line-height:1.03!important;letter-spacing:-.8px!important;overflow-wrap:anywhere;word-break:normal;margin:14px 0 20px!important}.lead{font-size:16px!important;line-height:1.48!important}.eyebrow{font-size:10px!important;letter-spacing:.12em!important}.hero-actions{gap:10px}.gallery figure,.gallery .g1,.gallery .g2,.gallery .g3,.gallery .g4,.gallery .g5,.gallery .g6{height:auto!important;aspect-ratio:4/5}.gallery .g2{aspect-ratio:16/10}.gallery picture,.gallery img{width:100%!important;height:100%!important}.gallery img{object-fit:cover!important}.gallery figcaption{font-size:12px!important;padding:10px 12px!important}}@media(max-width:390px){.hero-copy h1{font-size:34px!important;letter-spacing:-.5px!important}}`;document.head.appendChild(mobileFix);

const replacePicture=(selector,src)=>{document.querySelectorAll(selector).forEach(img=>{const picture=img.closest('picture');if(picture)picture.querySelectorAll('source').forEach(s=>s.remove());img.style.display='block';img.src=src;img.removeAttribute('srcset')})};
replacePicture('.gallery .g1 img','assets/images/living-room-v2.jpg');
replacePicture('.gallery .g2 img','assets/images/kitchen-v2.jpg');
replacePicture('.furniture img','assets/images/kitchen-v2.jpg');
const heroMedia=document.querySelector('.hero-media');if(heroMedia){heroMedia.style.backgroundImage="url('assets/images/living-room-v2.jpg')";heroMedia.style.backgroundPosition='center 45%'}

document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.style.background='#ddd';img.alt=img.alt||'Фотография работы временно недоступна'},{once:true}));

const menuBtn=document.querySelector('.menu-btn');const nav=document.querySelector('.nav');if(menuBtn&&nav){menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}))}

const form=document.getElementById('lead-form');const note=document.getElementById('form-note');if(form){form.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(form);const name=(data.get('name')||'').toString().trim();const phone=(data.get('phone')||'').toString().trim();const task=(data.get('task')||'').toString().trim();const text=`Здравствуйте, Володя! Хочу обсудить ремонт.${name?`\nИмя: ${name}`:''}${phone?`\nТелефон: ${phone}`:''}${task?`\nЗадача: ${task}`:''}`;let copied=false;try{await navigator.clipboard.writeText(text);copied=true}catch(err){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();copied=document.execCommand('copy');ta.remove()}if(note){note.textContent=copied?'Заявка скопирована. Открываю страницу ВКонтакте — вставьте текст в сообщение.':'Открываю ВКонтакте. Скопируйте данные из формы вручную.'}setTimeout(()=>window.open('https://vk.ru/id1084594994','_blank','noopener'),150)})}